// client/src/components/tools/Base64Encoder.vue
<template>
  <div class="base64-encoder">
    <el-card class="input-card">
      <template #header>
        <h3>输入文本</h3>
      </template>
      <el-input
        v-model="inputText"
        type="textarea"
        placeholder="输入要编码/解码的文本..."
        :rows="6"
      />
      <div class="button-group">
        <el-button 
          type="primary" 
          :disabled="!inputText.trim()"
          @click="encode"
        >
          <el-icon><Top /></el-icon>
          编码为Base64
        </el-button>
        <el-button 
          type="warning" 
          :disabled="!inputText.trim()"
          @click="decode"
        >
          <el-icon><Bottom /></el-icon>
          从Base64解码
        </el-button>
        <el-button @click="clear">
          <el-icon><Delete /></el-icon>
          清除
        </el-button>
      </div>
    </el-card>

    <el-card v-if="encodedResult" class="result-card">
      <template #header>
        <div class="result-header">
          <h3>Base64编码结果</h3>
          <el-button
            type="primary"
            size="small"
            @click="copyToClipboard(encodedResult)"
          >
            <el-icon><DocumentCopy /></el-icon>
            复制
          </el-button>
        </div>
      </template>
      <div class="result-content">{{ encodedResult }}</div>
    </el-card>

    <el-card v-if="decodedResult" class="result-card">
      <template #header>
        <div class="result-header">
          <h3>解码结果</h3>
          <el-button
            type="primary"
            size="small"
            @click="copyToClipboard(decodedResult)"
          >
            <el-icon><DocumentCopy /></el-icon>
            复制
          </el-button>
        </div>
      </template>
      <div class="result-content">{{ decodedResult }}</div>
    </el-card>

    <el-card class="info-card">
      <template #header>
        <h3>关于Base64编码</h3>
      </template>
      <p>
        Base64是一种二进制到文本的编码方案，将二进制数据表示为ASCII字符串格式。
        它通常用于编码电子邮件附件、数据URL和Web应用程序中的数据。
      </p>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Top, Bottom, Delete, DocumentCopy } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'

const inputText = ref('')
const encodedResult = ref('')
const decodedResult = ref('')

const encode = () => {
  try {
    const result = btoa(unescape(encodeURIComponent(inputText.value)))
    encodedResult.value = result
    decodedResult.value = ''
    ElMessage.success('编码成功')
  } catch (error) {
    ElMessage.error('编码失败')
  }
}

const decode = () => {
  try {
    const result = decodeURIComponent(escape(atob(inputText.value)))
    decodedResult.value = result
    encodedResult.value = ''
    ElMessage.success('解码成功')
  } catch (error) {
    ElMessage.error('解码失败，请检查Base64格式是否正确')
  }
}

const clear = () => {
  inputText.value = ''
  encodedResult.value = ''
  decodedResult.value = ''
}

const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text)
    ElMessage.success('已复制到剪贴板')
  } catch (error) {
    ElMessage.error('复制失败')
  }
}
</script>

<style scoped>
.base64-encoder {
  max-width: 800px;
  margin: 0 auto;
}

.input-card,
.result-card,
.info-card {
  margin-bottom: 1.5rem;
}

.button-group {
  margin-top: 1rem;
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
}

.result-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.result-header h3 {
  margin: 0;
}

.result-content {
  background: #f9fafb;
  border-radius: 6px;
  padding: 1rem;
  font-family: 'Monaco', 'Menlo', monospace;
  font-size: 0.875rem;
  word-break: break-all;
  color: #374151;
  min-height: 100px;
}

.info-card p {
  margin: 0;
  color: #6b7280;
  line-height: 1.6;
}
</style>

// client/src/components/tools/base64-encoder.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";

export default function Base64Encoder() {
  const [input, setInput] = useState("");
  const [encoded, setEncoded] = useState("");
  const [decoded, setDecoded] = useState("");
  const { toast } = useToast();

  const encode = () => {
    try {
      const result = btoa(unescape(encodeURIComponent(input)));
      setEncoded(result);
    } catch (error) {
      toast({
        title: "Encoding Error",
        description: "Failed to encode the text",
        variant: "destructive"
      });
    }
  };

  const decode = () => {
    try {
      const result = decodeURIComponent(escape(atob(input)));
      setDecoded(result);
    } catch (error) {
      toast({
        title: "Decoding Error",
        description: "Invalid Base64 string",
        variant: "destructive"
      });
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied to clipboard",
      description: "Text has been copied to your clipboard",
    });
  };

  const clear = () => {
    setInput("");
    setEncoded("");
    setDecoded("");
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Input */}
      <Card>
        <CardHeader>
          <CardTitle>Input Text</CardTitle>
        </CardHeader>
        <CardContent>
          <Textarea
            placeholder="Enter text to encode/decode..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            className="min-h-[120px]"
          />
          <div className="flex gap-2 mt-4">
            <Button onClick={encode} disabled={!input.trim()}>
              <i className="fas fa-arrow-up mr-2"></i>
              Encode to Base64
            </Button>
            <Button onClick={decode} disabled={!input.trim()} variant="outline">
              <i className="fas fa-arrow-down mr-2"></i>
              Decode from Base64
            </Button>
            <Button onClick={clear} variant="outline">
              <i className="fas fa-trash mr-2"></i>
              Clear
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Encoded Output */}
      {encoded && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Base64 Encoded</CardTitle>
              <Button
                variant="outline"
                size="sm"
                onClick={() => copyToClipboard(encoded)}
              >
                <i className="fas fa-copy mr-2"></i>
                Copy
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div className="bg-slate-50 rounded-lg p-4 font-mono text-sm break-all">
              {encoded}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Decoded Output */}
      {decoded && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Decoded Text</CardTitle>
              <Button
                variant="outline"
                size="sm"
                onClick={() => copyToClipboard(decoded)}
              >
                <i className="fas fa-copy mr-2"></i>
                Copy
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div className="bg-slate-50 rounded-lg p-4 font-mono text-sm break-words">
              {decoded}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Info */}
      <Card>
        <CardHeader>
          <CardTitle>About Base64 Encoding</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-slate-600">
            Base64 is a binary-to-text encoding scheme that represents binary data in an ASCII string format.
            It's commonly used for encoding data in email attachments, data URLs, and web applications.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
