// client/src/components/tools/HashGenerator.vue
<template>
  <div class="hash-generator">
    <el-card class="input-card">
      <template #header>
        <h3>哈希生成器</h3>
      </template>
      
      <el-form>
        <el-form-item label="输入文本">
          <el-input
            v-model="inputText"
            type="textarea"
            placeholder="输入要生成哈希的文本..."
            :rows="6"
          />
        </el-form-item>
        
        <el-form-item>
          <el-button 
            type="primary" 
            :disabled="!inputText.trim()"
            @click="generateHashes"
          >
            <el-icon><Lock /></el-icon>
            生成哈希值
          </el-button>
          <el-button @click="clear">
            <el-icon><Delete /></el-icon>
            清除
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <div v-if="Object.keys(hashes).length > 0" class="hash-results">
      <el-card 
        v-for="hashType in hashTypes" 
        :key="hashType.key"
        v-show="hashes[hashType.key]"
        class="hash-card"
      >
        <template #header>
          <div class="hash-header">
            <div>
              <h4>{{ hashType.name }}</h4>
              <p class="hash-desc">{{ hashType.description }}</p>
            </div>
            <el-button
              type="primary"
              size="small"
              @click="copyToClipboard(hashes[hashType.key], hashType.name)"
            >
              <el-icon><DocumentCopy /></el-icon>
              复制
            </el-button>
          </div>
        </template>
        
        <div class="hash-result">
          {{ hashes[hashType.key] }}
        </div>
      </el-card>
    </div>

    <el-card class="info-card">
      <template #header>
        <h3>关于哈希函数</h3>
      </template>
      <p>
        哈希函数是将输入数据转换为固定大小字符串的数学算法。
        它们通常用于数据完整性验证、密码存储和数字签名。
        每个哈希算法都会为输入数据产生唯一的"指纹"。
      </p>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { Lock, Delete, DocumentCopy } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'

const inputText = ref('')
const hashes = reactive<Record<string, string>>({})

const hashTypes = [
  { key: 'sha1', name: 'SHA-1', description: '160位哈希函数' },
  { key: 'sha256', name: 'SHA-256', description: '256位哈希函数' },
  { key: 'sha384', name: 'SHA-384', description: '384位哈希函数' },
  { key: 'sha512', name: 'SHA-512', description: '512位哈希函数' },
  { key: 'simple', name: '简单哈希', description: '用于演示的基础哈希' }
]

const generateHashes = async () => {
  if (!inputText.value.trim()) return

  const encoder = new TextEncoder()
  const data = encoder.encode(inputText.value)

  try {
    // 清空之前的结果
    Object.keys(hashes).forEach(key => delete hashes[key])

    // SHA-1
    const sha1Buffer = await crypto.subtle.digest('SHA-1', data)
    hashes.sha1 = Array.from(new Uint8Array(sha1Buffer))
      .map(b => b.toString(16).padStart(2, '0'))
      .join('')

    // SHA-256
    const sha256Buffer = await crypto.subtle.digest('SHA-256', data)
    hashes.sha256 = Array.from(new Uint8Array(sha256Buffer))
      .map(b => b.toString(16).padStart(2, '0'))
      .join('')

    // SHA-384
    const sha384Buffer = await crypto.subtle.digest('SHA-384', data)
    hashes.sha384 = Array.from(new Uint8Array(sha384Buffer))
      .map(b => b.toString(16).padStart(2, '0'))
      .join('')

    // SHA-512
    const sha512Buffer = await crypto.subtle.digest('SHA-512', data)
    hashes.sha512 = Array.from(new Uint8Array(sha512Buffer))
      .map(b => b.toString(16).padStart(2, '0'))
      .join('')

    // 简单哈希（用于演示，非加密安全）
    let hash = 0
    for (let i = 0; i < inputText.value.length; i++) {
      const char = inputText.value.charCodeAt(i)
      hash = ((hash << 5) - hash) + char
      hash = hash & hash // 转换为32位整数
    }
    hashes.simple = Math.abs(hash).toString(16)

    ElMessage.success('哈希值生成成功')
  } catch (error) {
    ElMessage.error('生成哈希值失败')
  }
}

const clear = () => {
  inputText.value = ''
  Object.keys(hashes).forEach(key => delete hashes[key])
}

const copyToClipboard = async (text: string, type: string) => {
  try {
    await navigator.clipboard.writeText(text)
    ElMessage.success(`${type}哈希值已复制到剪贴板`)
  } catch (error) {
    ElMessage.error('复制失败')
  }
}
</script>

<style scoped>
.hash-generator {
  max-width: 800px;
  margin: 0 auto;
}

.input-card,
.info-card {
  margin-bottom: 1.5rem;
}

.hash-results {
  display: grid;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.hash-card {
  break-inside: avoid;
}

.hash-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.hash-header h4 {
  margin: 0 0 0.25rem 0;
  font-size: 1rem;
  font-weight: 600;
}

.hash-desc {
  margin: 0;
  font-size: 0.875rem;
  color: #6b7280;
}

.hash-result {
  background: #f9fafb;
  border-radius: 6px;
  padding: 1rem;
  font-family: 'Monaco', 'Menlo', monospace;
  font-size: 0.875rem;
  word-break: break-all;
  color: #374151;
  min-height: 60px;
}

.info-card p {
  margin: 0;
  color: #6b7280;
  line-height: 1.6;
}
</style>

// client/src/components/tools/hash-generator.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";

export default function HashGenerator() {
  const [input, setInput] = useState("");
  const [hashes, setHashes] = useState<Record<string, string>>({});
  const { toast } = useToast();

  const generateHashes = async () => {
    if (!input.trim()) return;

    const encoder = new TextEncoder();
    const data = encoder.encode(input);

    try {
      const results: Record<string, string> = {};

      // SHA-1
      const sha1Buffer = await crypto.subtle.digest('SHA-1', data);
      results.sha1 = Array.from(new Uint8Array(sha1Buffer))
        .map(b => b.toString(16).padStart(2, '0'))
        .join('');

      // SHA-256
      const sha256Buffer = await crypto.subtle.digest('SHA-256', data);
      results.sha256 = Array.from(new Uint8Array(sha256Buffer))
        .map(b => b.toString(16).padStart(2, '0'))
        .join('');

      // SHA-384
      const sha384Buffer = await crypto.subtle.digest('SHA-384', data);
      results.sha384 = Array.from(new Uint8Array(sha384Buffer))
        .map(b => b.toString(16).padStart(2, '0'))
        .join('');

      // SHA-512
      const sha512Buffer = await crypto.subtle.digest('SHA-512', data);
      results.sha512 = Array.from(new Uint8Array(sha512Buffer))
        .map(b => b.toString(16).padStart(2, '0'))
        .join('');

      // Simple MD5-like hash (not cryptographically secure, for demo purposes)
      let hash = 0;
      for (let i = 0; i < input.length; i++) {
        const char = input.charCodeAt(i);
        hash = ((hash << 5) - hash) + char;
        hash = hash & hash; // Convert to 32-bit integer
      }
      results.simple = Math.abs(hash).toString(16);

      setHashes(results);
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate hashes",
        variant: "destructive"
      });
    }
  };

  const copyToClipboard = (text: string, type: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied to clipboard",
      description: `${type.toUpperCase()} hash copied to clipboard`,
    });
  };

  const clear = () => {
    setInput("");
    setHashes({});
  };

  const hashTypes = [
    { key: 'sha1', name: 'SHA-1', description: '160-bit hash function' },
    { key: 'sha256', name: 'SHA-256', description: '256-bit hash function' },
    { key: 'sha384', name: 'SHA-384', description: '384-bit hash function' },
    { key: 'sha512', name: 'SHA-512', description: '512-bit hash function' },
    { key: 'simple', name: 'Simple Hash', description: 'Basic hash for demonstration' }
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Input */}
      <Card>
        <CardHeader>
          <CardTitle>Hash Generator</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div>
              <Label htmlFor="input-text">Input Text</Label>
              <Textarea
                id="input-text"
                placeholder="Enter text to generate hashes..."
                value={input}
                onChange={(e) => setInput(e.target.value)}
                className="min-h-[120px]"
              />
            </div>
            <div className="flex gap-2">
              <Button onClick={generateHashes} disabled={!input.trim()}>
                <i className="fas fa-fingerprint mr-2"></i>
                Generate Hashes
              </Button>
              <Button onClick={clear} variant="outline">
                <i className="fas fa-trash mr-2"></i>
                Clear
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Hash Results */}
      {Object.keys(hashes).length > 0 && (
        <div className="space-y-4">
          {hashTypes.map(({ key, name, description }) => {
            if (!hashes[key]) return null;
            
            return (
              <Card key={key}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div>
                      <CardTitle className="text-lg">{name}</CardTitle>
                      <p className="text-sm text-slate-500">{description}</p>
                    </div>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => copyToClipboard(hashes[key], name)}
                    >
                      <i className="fas fa-copy mr-2"></i>
                      Copy
                    </Button>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="bg-slate-50 rounded-lg p-4 font-mono text-sm break-all">
                    {hashes[key]}
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}

      {/* Info */}
      <Card>
        <CardHeader>
          <CardTitle>About Hash Functions</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-slate-600">
            Hash functions are mathematical algorithms that convert input data into a fixed-size string of characters.
            They are commonly used for data integrity verification, password storage, and digital signatures.
            Each hash algorithm produces a unique "fingerprint" of the input data.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
