// client/src/components/tools/password-generator.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Slider } from "@/components/ui/slider";
import { useToast } from "@/hooks/use-toast";

export default function PasswordGenerator() {
  const [length, setLength] = useState([12]);
  const [includeUppercase, setIncludeUppercase] = useState(true);
  const [includeLowercase, setIncludeLowercase] = useState(true);
  const [includeNumbers, setIncludeNumbers] = useState(true);
  const [includeSymbols, setIncludeSymbols] = useState(false);
  const [excludeSimilar, setExcludeSimilar] = useState(false);
  const [password, setPassword] = useState("");
  const [history, setHistory] = useState<string[]>([]);
  const { toast } = useToast();

  const generatePassword = () => {
    let charset = "";
    let similarChars = "il1Lo0O";

    if (includeUppercase) charset += "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    if (includeLowercase) charset += "abcdefghijklmnopqrstuvwxyz";
    if (includeNumbers) charset += "0123456789";
    if (includeSymbols) charset += "!@#$%^&*()_+-=[]{}|;:,.<>?";

    if (excludeSimilar) {
      charset = charset.split("").filter(char => !similarChars.includes(char)).join("");
    }

    if (!charset) {
      toast({
        title: "Error",
        description: "Please select at least one character type",
        variant: "destructive"
      });
      return;
    }

    let newPassword = "";
    for (let i = 0; i < length[0]; i++) {
      newPassword += charset.charAt(Math.floor(Math.random() * charset.length));
    }

    setPassword(newPassword);
    setHistory(prev => [newPassword, ...prev.slice(0, 9)]);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied to clipboard",
      description: "Password copied to clipboard",
    });
  };

  const getStrengthScore = (pass: string) => {
    let score = 0;
    if (pass.length >= 8) score += 1;
    if (pass.length >= 12) score += 1;
    if (/[a-z]/.test(pass)) score += 1;
    if (/[A-Z]/.test(pass)) score += 1;
    if (/[0-9]/.test(pass)) score += 1;
    if (/[^A-Za-z0-9]/.test(pass)) score += 1;
    return score;
  };

  const getStrengthLabel = (score: number) => {
    if (score <= 2) return { label: "Weak", color: "text-red-600", bg: "bg-red-100" };
    if (score <= 4) return { label: "Medium", color: "text-yellow-600", bg: "bg-yellow-100" };
    return { label: "Strong", color: "text-green-600", bg: "bg-green-100" };
  };

  const strength = password ? getStrengthLabel(getStrengthScore(password)) : null;

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Settings */}
      <Card>
        <CardHeader>
          <CardTitle>Password Settings</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div>
            <Label>Length: {length[0]}</Label>
            <Slider
              value={length}
              onValueChange={setLength}
              max={50}
              min={4}
              step={1}
              className="mt-2"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="flex items-center space-x-2">
              <Checkbox
                id="uppercase"
                checked={includeUppercase}
                onCheckedChange={setIncludeUppercase}
              />
              <Label htmlFor="uppercase">Uppercase (A-Z)</Label>
            </div>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="lowercase"
                checked={includeLowercase}
                onCheckedChange={setIncludeLowercase}
              />
              <Label htmlFor="lowercase">Lowercase (a-z)</Label>
            </div>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="numbers"
                checked={includeNumbers}
                onCheckedChange={setIncludeNumbers}
              />
              <Label htmlFor="numbers">Numbers (0-9)</Label>
            </div>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="symbols"
                checked={includeSymbols}
                onCheckedChange={setIncludeSymbols}
              />
              <Label htmlFor="symbols">Symbols (!@#$%)</Label>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <Checkbox
              id="exclude-similar"
              checked={excludeSimilar}
              onCheckedChange={setExcludeSimilar}
            />
            <Label htmlFor="exclude-similar">Exclude similar characters (il1Lo0O)</Label>
          </div>

          <Button onClick={generatePassword} className="w-full">
            <i className="fas fa-key mr-2"></i>
            Generate Password
          </Button>
        </CardContent>
      </Card>

      {/* Generated Password */}
      {password && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Generated Password</CardTitle>
              {strength && (
                <span className={`px-2 py-1 text-xs font-semibold rounded ${strength.bg} ${strength.color}`}>
                  {strength.label}
                </span>
              )}
            </div>
          </CardHeader>
          <CardContent>
            <div className="flex items-center space-x-2">
              <Input
                value={password}
                readOnly
                className="font-mono"
              />
              <Button
                variant="outline"
                onClick={() => copyToClipboard(password)}
              >
                <i className="fas fa-copy"></i>
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Password History */}
      {history.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Recent Passwords</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {history.map((historyPassword, index) => (
                <div key={index} className="flex items-center justify-between p-2 bg-slate-50 rounded">
                  <span className="font-mono text-sm truncate flex-1 mr-2">{historyPassword}</span>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => copyToClipboard(historyPassword)}
                  >
                    <i className="fas fa-copy"></i>
                  </Button>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

// client/src/components/tools/PasswordGenerator.vue
<template>
  <div class="password-generator">
    <el-card class="settings-card">
      <template #header>
        <h3>密码设置</h3>
      </template>
      
      <el-form :model="settings" label-width="120px">
        <el-form-item :label="`长度: ${settings.length}`">
          <el-slider
            v-model="settings.length"
            :min="4"
            :max="50"
            show-stops
          />
        </el-form-item>

        <el-form-item label="字符类型">
          <div class="checkbox-group">
            <el-checkbox v-model="settings.includeUppercase">大写字母 (A-Z)</el-checkbox>
            <el-checkbox v-model="settings.includeLowercase">小写字母 (a-z)</el-checkbox>
            <el-checkbox v-model="settings.includeNumbers">数字 (0-9)</el-checkbox>
            <el-checkbox v-model="settings.includeSymbols">符号 (!@#$%)</el-checkbox>
          </div>
        </el-form-item>

        <el-form-item>
          <el-checkbox v-model="settings.excludeSimilar">
            排除相似字符 (il1Lo0O)
          </el-checkbox>
        </el-form-item>

        <el-form-item>
          <el-button type="primary" @click="generatePassword" style="width: 100%">
            <el-icon><Key /></el-icon>
            生成密码
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card v-if="generatedPassword" class="result-card">
      <template #header>
        <div class="result-header">
          <h3>生成的密码</h3>
          <el-tag :type="strengthTag.type" size="small">
            {{ strengthTag.label }}
          </el-tag>
        </div>
      </template>
      
      <div class="password-result">
        <el-input
          v-model="generatedPassword"
          readonly
          class="password-input"
        >
          <template #append>
            <el-button @click="copyToClipboard(generatedPassword)">
              <el-icon><DocumentCopy /></el-icon>
            </el-button>
          </template>
        </el-input>
      </div>
    </el-card>

    <el-card v-if="history.length > 0" class="history-card">
      <template #header>
        <h3>最近生成的密码</h3>
      </template>
      
      <div class="history-list">
        <div 
          v-for="(password, index) in history" 
          :key="index"
          class="history-item"
        >
          <span class="password-text">{{ password }}</span>
          <el-button
            size="small"
            @click="copyToClipboard(password)"
          >
            <el-icon><DocumentCopy /></el-icon>
          </el-button>
        </div>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, computed } from 'vue'
import { Key, DocumentCopy } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'

const settings = reactive({
  length: 12,
  includeUppercase: true,
  includeLowercase: true,
  includeNumbers: true,
  includeSymbols: false,
  excludeSimilar: false
})

const generatedPassword = ref('')
const history = ref<string[]>([])

const generatePassword = () => {
  let charset = ''
  const similarChars = 'il1Lo0O'

  if (settings.includeUppercase) charset += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  if (settings.includeLowercase) charset += 'abcdefghijklmnopqrstuvwxyz'
  if (settings.includeNumbers) charset += '0123456789'
  if (settings.includeSymbols) charset += '!@#$%^&*()_+-=[]{}|;:,.<>?'

  if (settings.excludeSimilar) {
    charset = charset.split('').filter(char => !similarChars.includes(char)).join('')
  }

  if (!charset) {
    ElMessage.error('请至少选择一种字符类型')
    return
  }

  let newPassword = ''
  for (let i = 0; i < settings.length; i++) {
    newPassword += charset.charAt(Math.floor(Math.random() * charset.length))
  }

  generatedPassword.value = newPassword
  history.value.unshift(newPassword)
  
  // 保留最近10个密码
  if (history.value.length > 10) {
    history.value = history.value.slice(0, 10)
  }
  
  ElMessage.success('密码生成成功')
}

const getStrengthScore = (password: string) => {
  let score = 0
  if (password.length >= 8) score += 1
  if (password.length >= 12) score += 1
  if (/[a-z]/.test(password)) score += 1
  if (/[A-Z]/.test(password)) score += 1
  if (/[0-9]/.test(password)) score += 1
  if (/[^A-Za-z0-9]/.test(password)) score += 1
  return score
}

const strengthTag = computed(() => {
  if (!generatedPassword.value) return { label: '', type: 'info' }
  
  const score = getStrengthScore(generatedPassword.value)
  if (score <= 2) return { label: '弱', type: 'danger' }
  if (score <= 4) return { label: '中', type: 'warning' }
  return { label: '强', type: 'success' }
})

const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text)
    ElMessage.success('密码已复制到剪贴板')
  } catch (error) {
    ElMessage.error('复制失败')
  }
}
</script>

<style scoped>
.password-generator {
  max-width: 600px;
  margin: 0 auto;
}

.settings-card,
.result-card,
.history-card {
  margin-bottom: 1.5rem;
}

.checkbox-group {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 0.5rem;
}

.result-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.result-header h3 {
  margin: 0;
}

.password-result {
  margin-bottom: 1rem;
}

.password-input :deep(.el-input__inner) {
  font-family: 'Monaco', 'Menlo', monospace;
  font-weight: 600;
}

.history-list {
  max-height: 200px;
  overflow-y: auto;
}

.history-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem;
  background: #f9fafb;
  border-radius: 6px;
  margin-bottom: 0.5rem;
}

.password-text {
  font-family: 'Monaco', 'Menlo', monospace;
  font-size: 0.875rem;
  flex: 1;
  margin-right: 1rem;
  word-break: break-all;
}

@media (max-width: 768px) {
  .checkbox-group {
    grid-template-columns: 1fr;
  }
}
</style>
