// client/src/components/tools/qr-generator.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function QRGenerator() {
  const [text, setText] = useState("");
  const [size, setSize] = useState("200");
  const [qrUrl, setQrUrl] = useState("");

  const generateQR = () => {
    if (!text.trim()) return;
    
    const encodedText = encodeURIComponent(text);
    const url = `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodedText}`;
    setQrUrl(url);
  };

  const downloadQR = () => {
    if (!qrUrl) return;
    
    const link = document.createElement('a');
    link.href = qrUrl;
    link.download = 'qrcode.png';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const clear = () => {
    setText("");
    setQrUrl("");
  };

  return (
    <div className="max-w-2xl mx-auto">
      <Card>
        <CardHeader>
          <CardTitle>QR Code Generator</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div>
            <Label htmlFor="text-input">Text or URL</Label>
            <Input
              id="text-input"
              placeholder="Enter text or URL to generate QR code..."
              value={text}
              onChange={(e) => setText(e.target.value)}
            />
          </div>

          <div>
            <Label htmlFor="size-select">Size</Label>
            <Select value={size} onValueChange={setSize}>
              <SelectTrigger>
                <SelectValue placeholder="Select size" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="150">150x150</SelectItem>
                <SelectItem value="200">200x200</SelectItem>
                <SelectItem value="300">300x300</SelectItem>
                <SelectItem value="400">400x400</SelectItem>
                <SelectItem value="500">500x500</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="flex gap-2">
            <Button onClick={generateQR} disabled={!text.trim()}>
              <i className="fas fa-qrcode mr-2"></i>
              Generate QR Code
            </Button>
            <Button onClick={clear} variant="outline">
              <i className="fas fa-trash mr-2"></i>
              Clear
            </Button>
          </div>

          {qrUrl && (
            <div className="text-center space-y-4">
              <div className="bg-slate-50 rounded-lg p-6 inline-block">
                <img 
                  src={qrUrl} 
                  alt="Generated QR Code" 
                  className="mx-auto"
                  style={{ width: `${size}px`, height: `${size}px` }}
                />
              </div>
              <div>
                <Button onClick={downloadQR}>
                  <i className="fas fa-download mr-2"></i>
                  Download QR Code
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      <Card className="mt-6">
        <CardHeader>
          <CardTitle>About QR Codes</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-slate-600">
            QR codes can store various types of data including text, URLs, contact information, 
            WiFi credentials, and more. They can be scanned by smartphones and other devices 
            with camera capabilities.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

// client/src/components/tools/QRGenerator.vue
<template>
  <div class="qr-generator">
    <el-card>
      <template #header>
        <h3>二维码生成器</h3>
      </template>
      
      <el-form :model="form" label-width="100px">
        <el-form-item label="文本或URL">
          <el-input
            v-model="form.text"
            placeholder="输入文本或URL来生成二维码..."
          />
        </el-form-item>

        <el-form-item label="尺寸">
          <el-select v-model="form.size" style="width: 200px">
            <el-option label="150x150" value="150" />
            <el-option label="200x200" value="200" />
            <el-option label="300x300" value="300" />
            <el-option label="400x400" value="400" />
            <el-option label="500x500" value="500" />
          </el-select>
        </el-form-item>

        <el-form-item>
          <el-button 
            type="primary" 
            :disabled="!form.text.trim()"
            @click="generateQR"
          >
            <el-icon><Picture /></el-icon>
            生成二维码
          </el-button>
          <el-button @click="clear">
            <el-icon><Delete /></el-icon>
            清除
          </el-button>
        </el-form-item>

        <el-form-item v-if="qrUrl">
          <div class="qr-result">
            <div class="qr-image-container">
              <img 
                :src="qrUrl" 
                alt="生成的二维码" 
                :style="{ width: `${form.size}px`, height: `${form.size}px` }"
              />
            </div>
            <div class="qr-actions">
              <el-button type="success" @click="downloadQR">
                <el-icon><Download /></el-icon>
                下载二维码
              </el-button>
            </div>
          </div>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="info-card">
      <template #header>
        <h3>关于二维码</h3>
      </template>
      <p>
        二维码可以存储各种类型的数据，包括文本、URL、联系人信息、WiFi凭据等。
        它们可以被智能手机和其他具有摄像头功能的设备扫描。
      </p>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import { Picture, Delete, Download } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'

const form = reactive({
  text: '',
  size: '200'
})

const qrUrl = ref('')

const generateQR = () => {
  if (!form.text.trim()) return
  
  const encodedText = encodeURIComponent(form.text)
  const url = `https://api.qrserver.com/v1/create-qr-code/?size=${form.size}x${form.size}&data=${encodedText}`
  qrUrl.value = url
  ElMessage.success('二维码生成成功')
}

const downloadQR = () => {
  if (!qrUrl.value) return
  
  const link = document.createElement('a')
  link.href = qrUrl.value
  link.download = 'qrcode.png'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  ElMessage.success('二维码下载成功')
}

const clear = () => {
  form.text = ''
  qrUrl.value = ''
}
</script>

<style scoped>
.qr-generator {
  max-width: 600px;
  margin: 0 auto;
}

.info-card {
  margin-top: 1.5rem;
}

.qr-result {
  text-align: center;
  width: 100%;
}

.qr-image-container {
  background: #f9fafb;
  border-radius: 8px;
  padding: 1.5rem;
  display: inline-block;
  margin-bottom: 1rem;
}

.qr-actions {
  margin-top: 1rem;
}

.info-card p {
  margin: 0;
  color: #6b7280;
  line-height: 1.6;
}
</style>
